# TODO: test if the environment variable is taking effect or it's the zsh rc files the second time (after dotfiles have been symlinked)

- name: Install fnm
  tags: homebrew
  environment:
    FNM_DIR: $HOME/.local/share/fnm
  community.general.homebrew:
    update_homebrew: true
    name: fnm
    state: present

- name: Install the latest LTS versions of Node and npm
  # assume this task will usually result in a change
  changed_when: true
  environment:
    FNM_DIR: $HOME/.local/share/fnm
  ansible.builtin.shell:
    cmd: fnm install --latest && fnm install --lts

- name: Install npm global packages
  # assume this task will usually result in a change
  changed_when: true
  ansible.builtin.command: npm install --global esbuild prettier
  # required dependency for "import cost" vscode extension
